### ISSUE TITLE
A question about the dataset labelling in scene 11

### ISSUE THREAD

**Issue by SimonSongg** [hlwang1124/GMRPD#2]
Hello~ I noticed that in scene 11, you labelled the yellow line on the ground as a edge of the drivable area. However, the area on the left side of the yellow line is also a drivable area. I am wondering the reason why you labelled it like this and what if I labelled the whole area between the wall and the grass as drivable area? 
![image](https://user-images.githubusercontent.com/70959938/119835905-d902aa80-bf33-11eb-8aff-2cb63c237537.png)

Thank you!!

**Comment by hlwang1124** [comment]
Hi, @SimonSongg . The reason is that the left side of the yellow line is a step, and you can see it clearly from the below depth image. If your robot can go through the step, I think you can label the whole area between the wall and the grass as the drivable area.

![depth](https://user-images.githubusercontent.com/25403947/124491863-50a2df80-dde6-11eb-86b7-36f7e7d0d7ee.png)

**Comment by SimonSongg** [comment]
Alright! I don't notice that the left side of the yellow line is a step. It makes sense now! Thanks.
